# i use the same config with vllm: https://github.com/vllm-project/vllm/blob/main/.gemini/config.yaml
have_fun: false  # Just review the code
code_review:
  comment_severity_threshold: HIGH  # Reduce quantity of comments
  pull_request_opened:
    summary: false  # Don't summarize the PR in a separate comment

